In [1]:
import pandas as pd

In [7]:
df = pd.read_json('C:\\Users\\H\\Downloads\\data-engineering-75\\day05\\weather_data_5_cities.json')

In [8]:
df.head(2)

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
0,"{'lon': 36.6822, 'lat': -3.3869}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 291.12, 'feels_like': 290.77, 'temp_m...",10000,"{'speed': 2.4, 'deg': 139, 'gust': 3.21}",{'all': 27},1790199067,"{'country': 'TZ', 'sunrise': 1790220119, 'suns...",10800,161325,Arusha,200,NaN
1,"{'lon': 34.7519, 'lat': 0.2827}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 289.33, 'feels_like': 289.41, 'temp_m...",10000,"{'speed': 1.4, 'deg': 45, 'gust': 1.4100000000...",{'all': 90},1790199069,"{'country': 'KE', 'sunrise': 1790220589, 'suns...",10800,195272,Kakamega,200,NaN

In [9]:
df.tail(2)

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
3,"{'lon': 3.3792, 'lat': 6.5244}","[{'id': 801, 'main': 'Clouds', 'description': ...",stations,"{'temp': 297.56, 'feels_like': 298.35, 'temp_m...",10000,"{'speed': 2.09, 'deg': 227, 'gust': 5.2}",{'all': 16},1790198936,"{'country': 'NG', 'sunrise': 1790141738, 'suns...",3600,2566677,Shogunle,200,NaN
4,"{'lon': 18.5628, 'lat': 4.3733}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 295.92, 'feels_like': 296.73, 'temp_m...",10000,"{'speed': 0.85, 'deg': 35, 'gust': 0.81}",{'all': 87},1790199322,"{'country': 'CF', 'sunrise': 1790138095, 'suns...",3600,2389853,Bangui,200,NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   coord       5 non-null      object
 1   weather     5 non-null      object
 2   base        5 non-null      str
 3   main        5 non-null      object
 4   visibility  5 non-null      int64
 5   wind        5 non-null      object
 6   clouds      5 non-null      object
 7   dt          5 non-null      int64
 8   sys         5 non-null      object
 9   timezone    5 non-null      int64
 10  id          5 non-null      int64
 11  name        5 non-null      str
 12  cod         5 non-null      int64
 13  rain        1 non-null      object
dtypes: int64(5), object(7), str(2)
memory usage: 692.0+ bytes

In [11]:
df.describe()

       visibility            dt      timezone            id    cod
count         5.0  5.000000e+00      5.000000  5.000000e+00    5.0
mean      10000.0  1.790199e+09   6480.000000  1.525486e+06  200.0
std           0.0  1.575960e+02   3943.602414  1.233272e+06    0.0
min       10000.0  1.790199e+09   3600.000000  1.613250e+05  200.0
25%       10000.0  1.790199e+09   3600.000000  1.952720e+05  200.0
50%       10000.0  1.790199e+09   3600.000000  2.314302e+06  200.0
75%       10000.0  1.790199e+09  10800.000000  2.389853e+06  200.0
max       10000.0  1.790199e+09  10800.000000  2.566677e+06  200.0

In [12]:
df["main"].iloc[0]

{'temp': 291.12,
 'feels_like': 290.77,
 'temp_min': 291.12,
 'temp_max': 291.12,
 'pressure': 1018,
 'humidity': 69,
 'sea_level': 1018,
 'grnd_level': 870}

In [13]:
df["weather"].iloc[0]

[{'id': 802,
  'main': 'Clouds',
  'description': 'scattered clouds',
  'icon': '03n'}]

In [14]:
df.isnull()

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
0,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [15]:
df.isnull().sum()

coord         0
weather       0
base          0
main          0
visibility    0
wind          0
clouds        0
dt            0
sys           0
timezone      0
id            0
name          0
cod           0
rain          4
dtype: int64

In [16]:
df.iloc[2]

coord                          {'lon': 15.2663, 'lat': -4.4419}
weather       [{'id': 500, 'main': 'Rain', 'description': 'l...
base                                                   stations
main          {'temp': 301.61, 'feels_like': 302.46, 'temp_m...
visibility                                                10000
wind                     {'speed': 1.69, 'deg': 2, 'gust': 2.7}
clouds                                             {'all': 100}
dt                                                   1790198936
sys           {'country': 'CD', 'sunrise': 1790138885, 'suns...
timezone                                                   3600
id                                                      2314302
name                                                   Kinshasa
cod                                                         200
rain                                 {'1h': 0.6900000000000001}
Name: 2, dtype: object

In [17]:
for index, row in df.iterrows():
    print(index, row['name'])

0 Arusha
1 Kakamega
2 Kinshasa
3 Shogunle
4 Bangui

In [19]:
df['name']

0      Arusha
1    Kakamega
2    Kinshasa
3    Shogunle
4      Bangui
Name: name, dtype: str

In [20]:
df['rain']

0                           NaN
1                           NaN
2    {'1h': 0.6900000000000001}
3                           NaN
4                           NaN
Name: rain, dtype: object

In [21]:
df.loc[df['rain'].isnull()]

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
0,"{'lon': 36.6822, 'lat': -3.3869}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 291.12, 'feels_like': 290.77, 'temp_m...",10000,"{'speed': 2.4, 'deg': 139, 'gust': 3.21}",{'all': 27},1790199067,"{'country': 'TZ', 'sunrise': 1790220119, 'suns...",10800,161325,Arusha,200,NaN
1,"{'lon': 34.7519, 'lat': 0.2827}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 289.33, 'feels_like': 289.41, 'temp_m...",10000,"{'speed': 1.4, 'deg': 45, 'gust': 1.4100000000...",{'all': 90},1790199069,"{'country': 'KE', 'sunrise': 1790220589, 'suns...",10800,195272,Kakamega,200,NaN
3,"{'lon': 3.3792, 'lat': 6.5244}","[{'id': 801, 'main': 'Clouds', 'description': ...",stations,"{'temp': 297.56, 'feels_like': 298.35, 'temp_m...",10000,"{'speed': 2.09, 'deg': 227, 'gust': 5.2}",{'all': 16},1790198936,"{'country': 'NG', 'sunrise': 1790141738, 'suns...",3600,2566677,Shogunle,200,NaN
4,"{'lon': 18.5628, 'lat': 4.3733}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 295.92, 'feels_like': 296.73, 'temp_m...",10000,"{'speed': 0.85, 'deg': 35, 'gust': 0.81}",{'all': 87},1790199322,"{'country': 'CF', 'sunrise': 1790138095, 'suns...",3600,2389853,Bangui,200,NaN

In [22]:
df.dropna(subset=['rain'])

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
2,"{'lon': 15.2663, 'lat': -4.4419}","[{'id': 500, 'main': 'Rain', 'description': 'l...",stations,"{'temp': 301.61, 'feels_like': 302.46, 'temp_m...",10000,"{'speed': 1.69, 'deg': 2, 'gust': 2.7}",{'all': 100},1790198936,"{'country': 'CD', 'sunrise': 1790138885, 'suns...",3600,2314302,Kinshasa,200,{'1h': 0.6900000000000001}

In [23]:
df.isnull().sum()

coord         0
weather       0
base          0
main          0
visibility    0
wind          0
clouds        0
dt            0
sys           0
timezone      0
id            0
name          0
cod           0
rain          4
dtype: int64

In [24]:
df  = df.dropna(subset=['rain'])

In [25]:
df.isnull().sum()

coord         0
weather       0
base          0
main          0
visibility    0
wind          0
clouds        0
dt            0
sys           0
timezone      0
id            0
name          0
cod           0
rain          0
dtype: int64

In [26]:
df2 = pd.read_json('C:\\Users\\H\\Downloads\\data-engineering-75\\day05\\weather_data_5_cities.json')

In [27]:
df2.columns

Index(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds',
       'dt', 'sys', 'timezone', 'id', 'name', 'cod', 'rain'],
      dtype='str')

In [28]:
df2.head(2)

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain
0,"{'lon': 36.6822, 'lat': -3.3869}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 291.12, 'feels_like': 290.77, 'temp_m...",10000,"{'speed': 2.4, 'deg': 139, 'gust': 3.21}",{'all': 27},1790199067,"{'country': 'TZ', 'sunrise': 1790220119, 'suns...",10800,161325,Arusha,200,NaN
1,"{'lon': 34.7519, 'lat': 0.2827}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 289.33, 'feels_like': 289.41, 'temp_m...",10000,"{'speed': 1.4, 'deg': 45, 'gust': 1.4100000000...",{'all': 90},1790199069,"{'country': 'KE', 'sunrise': 1790220589, 'suns...",10800,195272,Kakamega,200,NaN

In [29]:
df2['main'].iloc[0]

{'temp': 291.12,
 'feels_like': 290.77,
 'temp_min': 291.12,
 'temp_max': 291.12,
 'pressure': 1018,
 'humidity': 69,
 'sea_level': 1018,
 'grnd_level': 870}

In [ ]:
df2['main']

0    {'temp': 291.12, 'feels_like': 290.77, 'temp_m...
1    {'temp': 289.33, 'feels_like': 289.41, 'temp_m...
2    {'temp': 301.61, 'feels_like': 302.46, 'temp_m...
3    {'temp': 297.56, 'feels_like': 298.35, 'temp_m...
4    {'temp': 295.92, 'feels_like': 296.73, 'temp_m...
Name: main, dtype: object

In [33]:
df2['temperature'] = df2['main'].apply(lambda x: x['temp'])

In [34]:
df2.columns

Index(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds',
       'dt', 'sys', 'timezone', 'id', 'name', 'cod', 'rain', 'temperature'],
      dtype='str')

In [35]:
df2.iloc[0]

coord                           {'lon': 36.6822, 'lat': -3.3869}
weather        [{'id': 802, 'main': 'Clouds', 'description': ...
base                                                    stations
main           {'temp': 291.12, 'feels_like': 290.77, 'temp_m...
visibility                                                 10000
wind                    {'speed': 2.4, 'deg': 139, 'gust': 3.21}
clouds                                               {'all': 27}
dt                                                    1790199067
sys            {'country': 'TZ', 'sunrise': 1790220119, 'suns...
timezone                                                   10800
id                                                        161325
name                                                      Arusha
cod                                                          200
rain                                                         NaN
temperature                                               291.12
Name: 0, dtype: object

In [37]:
df2['temperature']

0    291.12
1    289.33
2    301.61
3    297.56
4    295.92
Name: temperature, dtype: float64

In [38]:
df3 = df2[df2['temperature'] > 295]

In [39]:
df3

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod,rain,temperature
2,"{'lon': 15.2663, 'lat': -4.4419}","[{'id': 500, 'main': 'Rain', 'description': 'l...",stations,"{'temp': 301.61, 'feels_like': 302.46, 'temp_m...",10000,"{'speed': 1.69, 'deg': 2, 'gust': 2.7}",{'all': 100},1790198936,"{'country': 'CD', 'sunrise': 1790138885, 'suns...",3600,2314302,Kinshasa,200,{'1h': 0.6900000000000001},301.61
3,"{'lon': 3.3792, 'lat': 6.5244}","[{'id': 801, 'main': 'Clouds', 'description': ...",stations,"{'temp': 297.56, 'feels_like': 298.35, 'temp_m...",10000,"{'speed': 2.09, 'deg': 227, 'gust': 5.2}",{'all': 16},1790198936,"{'country': 'NG', 'sunrise': 1790141738, 'suns...",3600,2566677,Shogunle,200,NaN,297.56
4,"{'lon': 18.5628, 'lat': 4.3733}","[{'id': 804, 'main': 'Clouds', 'description': ...",stations,"{'temp': 295.92, 'feels_like': 296.73, 'temp_m...",10000,"{'speed': 0.85, 'deg': 35, 'gust': 0.81}",{'all': 87},1790199322,"{'country': 'CF', 'sunrise': 1790138095, 'suns...",3600,2389853,Bangui,200,NaN,295.92